/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Aaoar1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Acain1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Acema1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Aciri1_iso/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Aciri1_meta/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Acral2/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Acrst1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Agabi_varbisH97_2/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Agabi_varbur_1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Agahy1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Altal1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Altbr1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Amamu1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Amath1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Amnli1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Amore1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Antav1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Antlo1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Antsi1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Apimo1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Aplpr1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Armga1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Armme1_1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Artbe1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Artel1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Artol1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Arxad1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Ascim1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Ascni1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Ascru1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Ascsa1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Ashgo1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Ashgo1_1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Aspac1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Aspbr1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Aspca3/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Aspcam1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Aspcl1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Aspfl1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Aspfo1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Aspfu1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Aspfu_A1163_1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Aspgl1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Aspka1_1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Aspni7/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Aspni_DSM_1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Aspni_NRRL3_1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Aspni_bvT_1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Aspnid1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Aspnov1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Aspoch1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Aspor1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Aspph1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Aspste1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Aspsy1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Aspte1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Asptu1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Aspve1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Aspwe1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Aspzo1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Atrsp2/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Aulhe2/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Aurde3_1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Aurpu_var_mel1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Aurpu_var_nam1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Aurpu_var_pul1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Aurpu_var_sub1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Aurvu1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Babin1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Bacci1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Basun1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Batde5/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Bauco1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Beaba1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Bimnz1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Bjead1_1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Blugr1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Boled1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Botbo1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Botci1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Botdo1_1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Bysci1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Cadsp1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Calco1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Calvi1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Canar1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Canca1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Canta1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Cante1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Catan1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Cenge3/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Cepal1_1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Cepfr1_1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/CerAGI/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Cersp1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Cersu1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Cerun2/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Cerzm1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Chagl_1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Chalo1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Chiap1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Chove1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/ClaPMI390/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Clael1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Clafu1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Clagr3/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Clapy1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Cloro1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Cocca1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/CocheC4_1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/CocheC5_3/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Cocim1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Coclu2/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Cocmi1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Cocsa1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Cocvi1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Coere1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Colca1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Coler1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Colfa1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Colgr1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Colhi1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Colso1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Colsu1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Colzo1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/ConPMI546/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Conco1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Conli1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Conlig1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Conpu1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Conth1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Copci1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Copci_AmutBmut1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Corca1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Corgl3/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Corma2/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Cormi1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Croqu1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Cryne_H99_1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Cryne_JEC21_1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Crypa2/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Cryvi1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Cucbe1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Cybja1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Cylto1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Dacsp1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Daequ1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/DalEC12_1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Debha1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Decga1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Dekbr2/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Delco1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Denbi1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Dicsq1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Didex1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Diocr1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Disac1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Dotse1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Dotsy1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Elmca1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Enccu1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Enche1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Encin1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Encro1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Entbi1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Erebi1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Eryha1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Eurhe1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Eutla1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Exigl1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Exova1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Fibra1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Fibsp1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Fishe1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Fomme1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Fompi3/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Fusfu1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Fusgr1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Fusox1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Fusox2/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Fusve1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Fusve2/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Galma1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Ganpr1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Gansp1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Glalo1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Gloac1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Gloci1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Gloin1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Glost2/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Glotr1_1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Grocl1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Guyne1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Gyman1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Gymau1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Gymch1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Gymci1_1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Gymlu1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Gyrli1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Hanpo2/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Hanva1_1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Hebcy2/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Hesve2finisherSC/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Hetan2/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Hetpy1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Hisca1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Hyabl1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Hydpi2/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Hydru2/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/HypCI4A_1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/HypCO275_1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/HypEC38_1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Hypbu1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Hypsu1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Hyspu1_1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Ilysp1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Jaaar1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Jamsp1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Karrh1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Kazaf1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Klula1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Lacam1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Lacbi2/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Laesu1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Leisp1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Lenfl1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Lenti6_1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Lenti7_1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Lepmu1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Leppa1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Leugo1_1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Leumo1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Lichy1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Linin1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Linth1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Lipst1_1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Lizem1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Lolmi1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Lopma1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Lopmy1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Lopni1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Lorju1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Macan1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Macfu1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Macph1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Maggr1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Magpo1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Malgl1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Malsy1_1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Marbr1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Marfi1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Marpt1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Maseb1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Meimi1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Melbi2/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Melli1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Mellp1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Melpu1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Melsp1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Melti1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Melva1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Metac1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Metan1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Metbi1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Micca1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Mictr1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Mixos1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Monha1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Monpe1_1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Monpu1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Monru1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Morco1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Morel1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Mucci2/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Mutel1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Mycfi2/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Mycgr3/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Myche1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Myrdu1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Myrin1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Mytre1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Nadfu1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Naifl1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Necha2/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Nempa1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Neofi1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Neole1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Neopa1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Neucr2/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Neucr_trp3_1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Neudi1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Neute_matA2/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Neute_mat_a1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Nieex1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Nosce1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Obbri1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Oidma1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Ompol1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Onnsc1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Ophdi1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Ophpc1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Orpsp1_1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Pacta1_2/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Panru1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Panst_KUC8834_1_1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Parbr1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Parsp1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Patat1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Paxam1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Paxin1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Paxru1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Penac1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Penbi1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Penbr2/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/PenbrAgRF18_1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Penca1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Pench1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/PenchWisc1_1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Pendi1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Penex1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Penfe1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Pengl1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Penja1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Penla1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Penox1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Penra1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Perma1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Phaal1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Phaca1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Phchr2/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Phisc1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Phlbr1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Phlgi1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Photr1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Phybl2/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Phycit1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Picme2/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Picpa1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Picst3/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Pieho1_1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Pilcr1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/PirE2_1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Pirin1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Pismi1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Pisti1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Plecu1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/PleosPC15_2/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/PleosPC9_1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Plesi1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Plicr1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Pneji1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Podan2/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Polar1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Polbr1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Polci1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Polfu1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Pospl1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/PosplRSB12_1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Psean1_1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Psehu1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Psehy1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Pucgr1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Pucst1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Punst1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Pycci1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Pycco1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Pycco1662_1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Pycsa1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Pyrco1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Pyrsp1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Pyrtr1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Pyrtt1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Ramac1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Rambr1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Rhich1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Rhier1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Rhili1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Rhimi1_1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Rhimi_ATCC11559_1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Rhimi_ATCC52814_1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Rhior3/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Rhisa1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Rhiso1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Rhivi1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Rhoba1_1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Rhodsp1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Rhomi1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Rhosp1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Rhoto1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Rhyru1_1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Ricme1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Rozal1_1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Rutfi1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Sacce1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/SacceM3707_1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/SacceM3836_1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/SacceM3837_1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/SacceM3838_1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/SacceM3839_1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/SacceYB210_1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Sacpr1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Saico1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Sarco1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Schco3/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Schco_LoeD_1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Schco_TatD_1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Schcy1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Schja1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Schoc1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Schpa1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Schpo1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Sclci1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Sclsc1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Sebve1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Sepmu1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Seppo1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Sepsp1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/SerlaS7_3_2/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/SerlaS7_9_2/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Serla_varsha1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Setho1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Settu1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Sisbr1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Sisni1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Sissu1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Sodal1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Spapa3/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Sphst1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Spofi1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Spoli1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Spore1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Sporo1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Spoth2/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Stagr1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Stano2/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Stasp1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Stehi1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Suibr1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Suigr1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Suihi1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Suilu1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Symat1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Symko1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Talma1_2/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Talst1_2/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Tapde1_1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Terbo2/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Ternu1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Tescy1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Theau1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Thega1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Themi1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Thian1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Thiap1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Thiar1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Thihy1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Thite2/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/ThoPMI491_1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Tilan2/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Tilwa1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Torde1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Torra1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Totfu1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Trace1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Traci1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Tralj1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Trave1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Treme1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Trepe1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Triab1_1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Trias1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Triat2/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Tribi1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Trich1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Trici4/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Trigu1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Triha1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Trilo3/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Trima3/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Triol1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Tripe1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Trire2/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/TrireRUTC30_1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Triru1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Trisp1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Triver1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/TriviGv29_8_2/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Tryvi1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Tubme1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Tulca1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Umbra1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Uncre1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Ustma1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Ustsp1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Valla1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Venin1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Venpi1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Veral1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Verda1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Veren1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Volvo1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Walic1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Walse1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Wesor1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Wican1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Wilmi1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Wolco1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Xanpa2/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Xerba1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Xylhe1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Yarli1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Zasce1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Zoprh1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Zygro1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Zymar1/data/genome.fasta
/home/tool/gmes/probuild --gc --seq /storage3/w/alexl/Fa/Zymps1/data/genome.fasta
